### ISSUE TITLE
Update redis-pq-demo notes on acapy playground

### ISSUE THREAD

**Issue by usingtechnology** [hyperledger/aries-mediator-service#104]
The ACA-Py demo/playground scripts have been [updated](https://github.com/hyperledger/aries-cloudagent-python/pull/2562).

redis-pq-demo uses the playground and needs to have the documentation updated. The changes will make testing simpler since the scripts have been containerized and no longer require python or installing requirements locally.

**Comment by Jsyro** [comment]
https://github.com/hyperledger/aries-mediator-service/pull/117
