### ISSUE TITLE
Does not work as a mediator because of routing issues

### ISSUE THREAD

**Issue by jleach** [hyperledger/aries-mediator-service#29]
As far as I can tell the current repo, as it is, wont work for any wallet because its missing either the ACA-py plugin from the toolbox (which Indecio uses in their running example) or a reverse proxy like  [Caddy](https://caddyserver.com/) to route both `wss://` and `https://` to the same port on the mediator. This means the docker stack will start but I don't think any wallet can meaningfully use it when running. Tested agains [Aries Bifold](https://github.com/hyperledger/aries-mobile-agent-react-native).

For context, the [Aries Bifold](https://github.com/hyperledger/aries-mobile-agent-react-native) wallet uses `https://` to respond to a connection invitation. Then it will open a DIDComm channel via `wss://` for subsequent messaging. The wallet cannot establish the `wss://` connection because `ngrok` is only forwarding `https://` back to the mediator container and, AFAIK, it can not be configured to do two ports simultaneously.

**Comment by PenguinTaro** [comment]
Hi @jleach I did the same configuration and set up the mediator for aries Bifold using von network. I am not using ngrok rather my ip, I was able to establish the connection but the area where I face issue is the communication part. It throws error for wss switching and renders this error message : Message is undeliverable to connection .
Please find the attachment for reference:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/99000637/226317731-b2f5a31d-7f54-4d00-b133-605ea194fc83.png)

**Comment by jainavinash845** [comment]
Hi @jleach 
We are using Aries acapy mediator . Using the invitation URl of mediator we tried connecting Aries bifold mobile app. We are follwoing error.

![MicrosoftTeams-image](https://github.com/hyperledger/aries-mediator-service/assets/44163302/0e7f2f7f-2236-4d81-89ea-8830902c2d06)
Please let me know , how can resolve it.

**Comment by jleach** [comment]
@jainavinash845 I would test the connectivity to see where it's failing. Is the problem the wallet can not talk to the mediator or the mediator to the wallet? Or perhaps the mediator cannot talk to the agent? That IP looks like a Bogon network for CGNAT. Maybe you're having problems because you are running behind CGNAT and the inbound connection is not making it through?

**Comment by jainavinash845** [comment]
Hi @jleach 
Thanx for your help.

In the initial while run the app changed the invitation url in the env file. And it does not redirect to wallet home page . It gives Time out error in the app and backed end Message unpack failed . 
I found the  backend error logs 
![MicrosoftTeams-image (1)](https://github.com/hyperledger/aries-mediator-service/assets/44163302/8cba08fa-9aa1-4082-b63f-4dd8cc34eb85)
Please let me know , how can resolve it.
.
