### ISSUE TITLE
Can I build and run Mediator service without ngRok ?

### ISSUE THREAD

**Issue by DucDA177** [hyperledger/aries-mediator-service#37]

**Comment by dinbtechit** [comment]
I had the exact same question. It would be nice to abstract the networking part out of aca-py. When running locally I prefer using `/etc/hosts`...if I want to expose the service. I can create a public IP & DNS in Azure. I don't know if I want to use ngrok.  Please advise.

**Comment by dinbtechit** [comment]
@swcurran - Thank you for the response! 🙌 . That's good to know people have deployed this service on public platforms. 

So going back to the original question of this issue.. Is it possible run the mediator locally without ngrok (Say I don't want to access the mediator outside my locaI machine)? I have the BC wallet, Von Network and issuer-kit running locally. I would like to run the mediator service in my local environment as well. Is that even possible? 

Based on the Readme instructions it seems like ngrok is mandatory to run the mediator locally. Please advise.

**Comment by swcurran** [comment]
A mediator needs a public endpoint, and so either you have to be running the mediator on a location that has a public endpoint or you need something like ngrok that provides a proxy to the mediator from a public endpoint.  The mediator is providing a persistent endpoint for the wallet.

Does that help, or am I still missing the question?

**Comment by dinbtechit** [comment]
Thank you so much for the explanation. That makes sense! 🙏

**Comment by jleach** [comment]
I think this issue is resolved. Closing.
