### ISSUE TITLE
Update instructions for starting the mediator and the load test agent on the same system

### ISSUE THREAD

**Issue by cvarjao** [hyperledger/aries-mediator-service#63]

**Comment by swcurran** [comment]
I was able to do get this working.  I'm not clear what the settings should be in the load testing `.env` file (other than the `MEDIATOR_URL`).  Connections work fine, but after the connection is established, there seems to be a long delay before anything happens.

It appears as is on my system (Linux, i7 older processor, 16GB), it takes about 2.8 seconds to establish a connection -- e.g. one agent, no competition. Crazy long, I would think, and there is queuing.

Very interested to know how it will work with Askar #64 .
