### ISSUE TITLE
Load test with using Askar wallet

### ISSUE THREAD

**Issue by cvarjao** [hyperledger/aries-mediator-service#64]
Update the mediator `docker-compose` (in the root folder) to use Askar instead of the Indy Wallet and note the change in performance.

**Comment by swcurran** [comment]
One for you @usingtechnology -- once you have it running.

Please submit a PR with at least instructions for doing this, or better, with Askar by default and instructions for reverting to the Indy SDK. If there is an easy way to switch between the two -- great, but we really should only be using Askar going forward.

**Comment by swcurran** [comment]
Figured out how to do this, and will submit a PR.
