### ISSUE TITLE
Moving the mediator between Kubernets cluster nodes caused connections to be lost

### ISSUE THREAD

**Issue by jleach** [hyperledger/aries-mediator-service#80]
When moving the entire stack (proxy, mediator, and database) to different Kubernets (k8s) nodes the WebSocket connections were lost and no longer work. This results in not being able to message existing connections and presents as a delay or missing subsequent credential offer: The next credential offer is not received but restarting the wallet and re-offering works.

**Comment by jleach** [comment]
I've tested agains the "test" mediator. It works fine. I've restarted the proxy, agent, and database. I made sure they're all on upgraded nodes. No problems. During Stephen's presentation there was 170 ppl on the call. Down to 100 now. Maybe it was caused by high load like @cvarjao earlier today mentioned.

**Comment by swcurran** [comment]
This is not good.  Is there a fix for this?  Presumably, the wallet has to detect that the websocket connection was lost, and then create a new one?

**Comment by WadeBarnes** [comment]
> During Stephen's presentation there was 170 ppl on the call. Down to 100 now. Maybe it was caused by high load like @cvarjao earlier today mentioned.

Of the people on the call only about 30 were registered with the Traction demo instance, and of those I think only a handful were trying to follow along with the demos.
